name: practica2
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.16.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_ripple: ^0.0.3
  flutter_bloc:
  equatable:

  # Firebase
  google_sign_in:
  firebase_auth:
  firebase_core:
  cloud_firestore:
  flutterfire_ui:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'images/headphones.jpg'

flutter:
  uses-material-design: true

  assets:
    - images/
